### ISSUE TITLE
Issue Importing SVG to JSON

### ISSUE THREAD

**Issue by anniemuse** [Z4Tech/SVG_GeometrizeJSON_Converter#1]
Hello, This seems like an awesome program. I'm new to Forza painter, but I'm hoping to learn how to accomplish the goal you've built this for. I'd love any insight you might have to help me get it to work. It seemed alright going from JSON to SVG, but I can't seem to get the JSON integrity back after it's edited in Illustrator and converted from SVG back to JSON. My preference is to use illustrator (CC21), but I also made a test with Inkscape (1.0), which doesn't look corrupt like the ai file does. Alas, still no luck >_> .. Any ideas? Thanks! 

I've attached my tests for your review:

Illustrator
JSON to SVG
[Geometrize JSON to SVG Converter.pdf](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8009259/Geometrize.JSON.to.SVG.Converter.pdf)

SVG to JSON
[Geometrize SVG & JSON Converter.pdf](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8009258/Geometrize.SVG.JSON.Converter.pdf)

Inkscape
![2022-02-05 18_41_15-Inkscape_Vinyl svg - Inkscape](https://user-images.githubusercontent.com/78004975/152665010-939abf0d-39f5-45e1-b939-c7a74c51ecdc.png)

Source Content
[5-AliceTapestry.zip](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8009261/5-AliceTapestry.zip)

**Comment by Z4Tech** [comment]
The problem is different software has different interpretations for the same geometry after editing. I tested on Inkscape and Illustrator 2020 with ellipses. Could you give me the SVG files saved by AI or Inkscape after your editing? I need to looked at the structure of the file and might need to modify the code.

**Comment by anniemuse** [comment]
[5-AliceTapestry.zip](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8009407/5-AliceTapestry.zip)

Here is the SVG and AI copies that look good in Illustrator, CC2021 (this ai ver. is not actually from the cloud as adobe wants tho, so if all else fails, there might be an issue with that. But even though idk how to use Inkscape, it wasn't exporting from my test file there either.

**Comment by anniemuse** [comment]
So hypothetically: ellipse, square, triangle shapes created in a vector program (illustrator or inkscape), can be converted from an SVG to a JSON compatible with forza painter. If so I'd also like to test a print with the following 16 shapes: 4 unique shapes, 4 with Transparent values, and two colors (white / black). I didn't have success with this test, but I can see the SVG code pulled from AI before saving, and it references four types of shapes: "rect" "circle" "polygon" .. sadly, after importing the converter doesn't output any shapes.

Desired Output:
![ForzaPainter-GeoTest-01 1](https://user-images.githubusercontent.com/78004975/152825234-1504799b-2d39-43dc-876e-2c19905dff1d.png)

I've attached my GeoTest files below:
[GeoTest.zip](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8016887/GeoTest.zip)

Thanks Z4Tech, I've been dreaming about this reality for years :)

**Comment by anniemuse** [comment]
Hey, I've been testing to see if there is anything I might be missing. Alas, still no luck with any of the following AI versions: CC20, 21, and 22., and only minor success using Inkscape (1.1.2). 

I've tried the process on the last 3 versions of Illustrator, and it outputs the same result in the converter preview, where the shapes do not retain their integrity. **That said, I haven't loved AI 2021, and I'm ready to move on to 2022.** 
Regardless, there must be something I'm missing on the AI SVG Options / Export window. Should it: be saved as SVG1.1? keep AI editing abilities? any advanced CSS setting?

I've tested with inkscape for the sake of troubleshooting, but this program is still very foreign to me... Nevertheless, it seems to be translating my changes when previewing on the converter, which is closer than I've gotten with Illustrator. Sadly, I'm still getting the No Geometry loaded error. Additionally, I noticed the JSON it spits out is formatted differently than the original JSON output from Forza Painter. Perhaps this is why the tool can't read the geometry? Thanks, again!

**Comment by anniemuse** [comment]
Please reach out on discord if you decide to work on this project again. For now I've got a trick that will work with your conversion tool using Inkscape and designs that were originally printed with Forza Painter. Even though, it seems this solution is limited to working with only circles. I'd still love to learn about building a vinyl with triangles and rectangles, so I'll keep trying to incorporate the other shapes for testing purposes. I was really hoping I could draw with circles, triangles, and rectangles in a vector art program and convert those designs to use with Forza Painter.

**Comment by anniemuse** [comment]
Attached is the workaround I'm using:
[SVG-to-JSON-fix.zip](https://github.com/Z4Tech/SVG_GeometrizeJSON_Converter/files/8096299/SVG-to-JSON-fix.zip)


Thanks so much for building this! -Annie
